[package]
name = "vfs-stale"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
numeric-enum-macro = "0.2.0"
spin = "0.9"

errno = { path = "../errno" }
kernel-sync = {  git = "https://github.com/tkf2019/kernel-sync" }